export const HOST_API = process.env.NEXT_PUBLIC_HOST_API
export const FACEBOOK_APP_ID = process.env.NEXT_PUBLIC_FACEBOOK_APP_ID || ''
export const FACEBOOK_PAGE_ID = process.env.NEXT_PUBLIC_FACEBOOK_PAGE_ID || ''
export const CAPTCHA_SITE_KEY = process.env.NEXT_PUBLIC_CAPTCHA_SITE_KEY || ''
export const GOOGLE_TAG_MANAGER_KEY =
  process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_KEY || ''
export const IMAGE_WESERV_URL = 'https://wsrv.nl'
export const CDN_IMAGE_SERVER = `${IMAGE_WESERV_URL}?url=${HOST_API}`

// PAGING
export const DEFAULT_PAGE_SIZE = 10
export const DEFAULT_PAGE_NUMBER = 1
export const DOTS = '...'

// COLOR
export const PRIMARY_COLOR = '#ffbe16'

export const REGEX_REMOVE_HTML = /(<([^>]+)>)/gi

export const SCREEN = {
  HOME_PAGE: 'HOME_PAGE',
  EMPLOYEE_PAGE: 'EMPLOYEE_PAGE',
  CONTACT_PAGE: 'CONTACT_PAGE',
  COMPANY_PAGE: 'COMPANY_PAGE',
  SERVICE_PAGE: 'SERVICE_PAGE',
  CALCULATOR_PAGE: 'CALCULATOR_PAGE',
  OURSTORY_PAGE: 'OURSTORY_PAGE',
  CASE_STUDIES_PAGE: 'CASE_STUDIES_PAGE',
  CASE_STUDIES_DETAIL_PAGE: 'CASE_STUDIES_DETAIL_PAGE',
  FAQ_PAGE: 'FAQ_PAGE',
  CAREERS_PAGE: 'CAREERS_PAGE',
  CAREERS_DETAIL_PAGE: 'CAREERS_DETAIL_PAGE',
  BLOG_PAGE: 'BLOG_PAGE',
  BLOG_DETAIL_PAGE: 'BLOG_DETAIL_PAGE',
  FETCHUNT_PAGE: 'FETCHUNT_PAGE',
}
